name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Install make
      run: |
        sudo apt-get update
        sudo apt-get install make

    - name: Build and Test
      run: |
        make deps
        # TODO Fix lint call, and all the other 'make' calls following it...
        #make ci-lint
        #make lint
        #make test | go-junit-report > $TEST_RESULTS/gotest/report.xml
        #make test

    - name: WriteGoList
      run: go list -json -m all > go.list

    - name: Scan with latest Nancy
      uses: sonatype-nexus-community/nancy-github-action@main
